import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, CarFront, Truck, Tractor, Sofa, BedDouble, Sparkles, ShieldCheck, Check, CalendarDays, MoveUpRight } from "lucide-react";
import { getGallery, getServices, getSettings, getTestimonials } from "@/lib/data";
import { defaultSettings, polishingSteps } from "@/lib/content";
import { SectionLabel, WhatsAppButton } from "@/components/ui";
import { FinalCta } from "@/components/footer";

const serviceIcons = [Sparkles, CarFront, Sofa, Truck, Tractor];
export default async function Home() {
  const [settings, services, gallery, testimonials] = await Promise.all([getSettings(), getServices(), getGallery(), getTestimonials()]);
  const defaultTitle = settings.hero_title === defaultSettings.hero_title;
  return <>
    <section className="hero"><div className="hero-grid-lines" aria-hidden="true" /><div className="container hero-inner">
      <div className="hero-copy"><div className="eyebrow"><span className="short-line" />ESTÉTICA AUTOMOTIVA & HIGIENIZAÇÃO</div>
        <h1>{defaultTitle ? <><span className="hero-line-wrap"><span className="hero-line">ESTÉTICA QUE</span></span><span className="hero-line-wrap"><span className="hero-line">DEVOLVE <span className="outline-text">O</span></span></span><span className="hero-line-wrap"><span className="hero-line copper-text">BRILHO.</span></span><span className="hero-heading-tail">AO SEU VEÍCULO.</span></> : <span className="custom-hero-title">{settings.hero_title}</span>}</h1>
        <p className="hero-description">{settings.hero_subtitle}</p><div className="hero-actions"><WhatsAppButton phone={settings.whatsapp}>Agendar pelo WhatsApp</WhatsAppButton><Link href="/servicos" className="text-link">Conhecer serviços <ArrowUpRight size={18} /></Link></div><p className="hero-note"><CalendarDays size={14} />Seu cuidado tem hora marcada. Atendimento com agendamento.</p>
      </div>
      <div className="hero-art"><div className="art-corner top-left" /><div className="art-corner bottom-right" /><div className="hero-art-image"><Image src="/images/garage-101-original.webp" alt="Identidade original da Garage 101: emblema metálico em cobre com carro e caminhão cromados" width={896} height={1197} sizes="(max-width: 600px) 95vw, (max-width: 900px) 80vw, 55vw" priority /></div><div className="art-caption"><span className="status-dot" />GARAGE 101<span>CUIDADO SEM ATALHOS.</span></div></div>
      <div className="hero-bottom"><span>BRILHO. PROTEÇÃO. VALORIZAÇÃO.</span><a href="#servicos" aria-label="Explorar os serviços">EXPLORE O CUIDADO <ArrowDown size={15} /></a></div>
    </div></section>
    <div className="signature-strip" aria-label="Áreas de atendimento"><div className="container"><span>CARROS</span><span className="copper-star">✦</span><span>CAMINHÕES</span><span className="copper-star">✦</span><span>MÁQUINAS AGRÍCOLAS</span><span className="copper-star">✦</span><span>ESTOFAMENTOS</span><span className="copper-star">✦</span></div></div>
    <section id="servicos" className="section services-section"><div className="container"><SectionLabel number="01">O QUE FAZEMOS</SectionLabel><div className="section-heading-row" data-reveal><h2 className="section-title">CADA DETALHE.<br /><span className="copper-text">UM NOVO PADRÃO.</span></h2><div><p className="muted">Da pintura ao interior. Do seu veículo à sua casa.<br />O cuidado certo faz toda a diferença.</p><Link href="/servicos" className="text-link">Explore nossos serviços <ArrowUpRight size={17} /></Link></div></div>
      <div className="service-list">{services.map((service, index) => { const Icon = serviceIcons[index % serviceIcons.length]; return <Link key={service.id} href={`/servicos/${service.slug}`} className="service-row" data-reveal><span className="service-index">0{index + 1}</span><div className="service-icon"><Icon size={27} strokeWidth={1.25} /></div><h3>{service.title}</h3><p>{service.short_description}</p><span className="circle-arrow"><ArrowUpRight size={21} /></span></Link>; })}</div>
    </div></section>
    <section className="polish-section section"><div className="container polish-grid"><div className="polish-left"><SectionLabel number="02">POLIMENTO COMPLETO</SectionLabel><h2 className="section-title">O BRILHO É SÓ<br /><span className="copper-text">O COMEÇO.</span></h2><p className="muted">Um processo completo.<br />Do primeiro cuidado ao acabamento final.</p><div className="polish-visual"><div className="polish-art"><Image src="/images/polimento-original.webp" alt="Arte original da Garage 101 com a frente de um carro escuro e brilhante" fill sizes="(max-width: 700px) 90vw, 40vw" style={{ objectFit: "cover", objectPosition: "center 30%" }} priority={false} /></div><div className="visual-label"><Sparkles size={15} />ACABAMENTO QUE FAZ A DIFERENÇA</div></div></div><div className="polish-right"><p className="process-intro">TUDO ISSO ESTÁ INCLUSO.</p><ol className="polish-steps">{polishingSteps.map(([title, description], index) => <li className="polish-step" key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{description}</p></div><Check size={18} /></li>)}</ol><div className="polish-bottom"><ShieldCheck size={26} strokeWidth={1.4} /><p>BRILHO. PROTEÇÃO.<br /><strong>VALORIZAÇÃO.</strong></p><Link href="/servicos/polimento-automotivo" aria-label="Conhecer o polimento completo"><ArrowUpRight size={27} /></Link></div></div></div></section>
    <section className="section vehicle-section"><div className="container"><SectionLabel number="03">DO CARRO AO PESADO</SectionLabel><div className="section-heading-row" data-reveal><h2 className="section-title">MUDA O PORTE.<br /><span className="copper-text">O CUIDADO CONTINUA.</span></h2><p className="muted">Carros, caminhões e máquinas agrícolas.<br />A mesma atenção em cada atendimento.</p></div><div className="vehicle-grid">{[{ title: "CARROS", Icon: CarFront, text: "Seu veículo. Seu orgulho.", href: "/servicos/polimento-automotivo", code: "01" }, { title: "CAMINHÕES", Icon: Truck, text: "Presença que merece cuidado.", href: "/servicos/caminhoes", code: "02" }, { title: "MÁQUINAS AGRÍCOLAS", Icon: Tractor, text: "O cuidado também chega ao campo.", href: "/servicos/maquinas-agricolas", code: "03" }].map(({ title, Icon, text, href, code }) => <Link href={href} className="vehicle-item" key={title} data-reveal><div className="vehicle-top"><span>G101 / {code}</span><ArrowUpRight size={23} /></div><Icon className="vehicle-illustration" strokeWidth={.7} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></Link>)}</div></div></section>
    <section className="results-teaser section"><div className="container results-teaser-inner"><div data-reveal><SectionLabel number="04">RESULTADOS REAIS</SectionLabel><h2 className="section-title">O DETALHE<br /><span className="copper-text">FAZ A DIFERENÇA.</span></h2><p className="muted">Cada resultado tem uma história de cuidado.</p><Link href="/resultados" className="button button-outline">Ver resultados <ArrowUpRight size={18} /></Link></div><div className="results-preview" data-reveal>{gallery.length ? <><Image src={gallery.find((item) => item.featured)?.after_image || gallery[0].after_image} alt={gallery.find((item) => item.featured)?.title || gallery[0].title} fill sizes="(max-width: 900px) 90vw, 50vw" /><Link href="/resultados" className="results-overlay">VEJA O ANTES E DEPOIS <ArrowUpRight /></Link></> : <><div className="results-ghost" aria-hidden="true">101<span>GARAGE</span></div><div className="results-empty-copy"><span className="eyebrow">CADA TRANSFORMAÇÃO, DE PERTO.</span><p>Estamos preparando nossa galeria.</p><span>Enquanto isso, converse com a gente<br />sobre o cuidado que você procura.</span></div></>}</div></div></section>
    <section className="upholstery-section section"><div className="container"><SectionLabel number="05">CUIDADO QUE VAI ALÉM</SectionLabel><div className="upholstery-heading" data-reveal><h2 className="section-title">LIMPEZA QUE SE VÊ.<br /><span className="copper-text">CONFORTO QUE SE SENTE.</span></h2><p className="muted">Higienização que vai além da aparência.<br />Uma atenção especial aos estofados da sua casa.</p></div><div className="upholstery-grid">{[{ title: "SOFÁS", Icon: Sofa, text: "Seu lugar de descanso, renovado.", benefits: ["Ajuda a remover sujeira acumulada", "Auxilia na remoção de odores", "Preserva o tecido", "Mais sensação de limpeza e conforto"] }, { title: "COLCHÕES", Icon: BedDouble, text: "Um cuidado a mais com o seu conforto.", benefits: ["Limpeza profunda", "Ajuda a remover poeira e odores", "Preservação do material", "Mais conforto no dia a dia"] }].map(({ title, Icon, text, benefits }) => <article className="upholstery-item" key={title} data-reveal><div className="upholstery-title"><Icon size={48} strokeWidth={1} /><h3>{title}</h3></div><p>{text}</p><ul>{benefits.map((benefit) => <li key={benefit}><Check size={15} />{benefit}</li>)}</ul></article>)}</div><div className="upholstery-cta"><span>CUIDAR DA SUA CASA TAMBÉM É CUIDAR DE VOCÊ.</span><WhatsAppButton phone={settings.whatsapp} message="Olá! Vim pelo site da Garage 101 e gostaria de um orçamento para higienização de estofamentos.">Solicitar orçamento</WhatsAppButton></div></div></section>
    <section className="section how-section"><div className="container"><SectionLabel number="06">SIMPLES, DO INÍCIO AO FIM</SectionLabel><h2 className="section-title" data-reveal>SEU PRÓXIMO CUIDADO.<br /><span className="copper-text">SEM COMPLICAÇÃO.</span></h2><ol className="how-steps">{["Entre em contato", "Conte o que precisa", "Combine um horário", "A gente cuida de tudo", "Receba o resultado"].map((title, index) => <li key={title} data-reveal><div><span>0{index + 1}</span>{index < 4 && <MoveUpRight size={17} />}</div><h3>{title}</h3></li>)}</ol><p className="schedule-note"><CalendarDays size={16} />O horário e o orçamento são combinados diretamente pelo WhatsApp.</p></div></section>
    {testimonials.length > 0 && <section className="section testimonials-section"><div className="container"><SectionLabel number="07">QUEM CONFIA NO NOSSO CUIDADO</SectionLabel><h2 className="section-title">A PALAVRA É SUA.</h2><div className="testimonials-grid">{testimonials.map((item) => <figure key={item.id}><div aria-label={`${item.rating} de 5 estrelas`} className="testimonial-stars">{"★".repeat(item.rating)}</div><blockquote>{item.text}</blockquote><figcaption>{item.name}</figcaption></figure>)}</div></div></section>}
    <FinalCta phone={settings.whatsapp} />
  </>;
}
